export const mockNouns = [
  {
    id: "n1",
    german_noun: "Tisch",
    article: "der",
    english_meaning: "table",
    plural: "die Tische",
    example_sentence: "Der Tisch ist groß und aus Holz.",
    english_translation: "The table is big and made of wood.",
    cefr_level: "A1",
    memory_tip: "Think of a table where you eat every day.",
    image_url: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n2",
    german_noun: "Lampe",
    article: "die",
    english_meaning: "lamp",
    plural: "die Lampen",
    example_sentence: "Die Lampe auf dem Schreibtisch ist sehr hell.",
    english_translation: "The lamp on the desk is very bright.",
    cefr_level: "A1",
    memory_tip: "Think of a bright lamp lighting up a dark room.",
    image_url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n3",
    german_noun: "Buch",
    article: "das",
    english_meaning: "book",
    plural: "die Bücher",
    example_sentence: "Das Buch ist spannend und lehrreich.",
    english_translation: "The book is exciting and educational.",
    cefr_level: "A1",
    memory_tip: "Think of your favorite book on a shelf.",
    image_url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n4",
    german_noun: "Stuhl",
    article: "der",
    english_meaning: "chair",
    plural: "die Stühle",
    example_sentence: "Der Stuhl ist sehr bequem.",
    english_translation: "The chair is very comfortable.",
    cefr_level: "A1",
    memory_tip: "Think of sitting comfortably on a chair.",
    image_url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n5",
    german_noun: "Tür",
    article: "die",
    english_meaning: "door",
    plural: "die Türen",
    example_sentence: "Bitte schließen Sie die Tür.",
    english_translation: "Please close the door.",
    cefr_level: "A1",
    memory_tip: "Think of a door opening to a new room.",
    image_url: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n6",
    german_noun: "Fenster",
    article: "das",
    english_meaning: "window",
    plural: "die Fenster",
    example_sentence: "Ich öffne das Fenster, um frische Luft hereinzulassen.",
    english_translation: "I open the window to let in fresh air.",
    cefr_level: "A1",
    memory_tip: "Think of looking out of a window.",
    image_url: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n7",
    german_noun: "Apfel",
    article: "der",
    english_meaning: "apple",
    plural: "die Äpfel",
    example_sentence: "Der Apfel ist rot und süß.",
    english_translation: "The apple is red and sweet.",
    cefr_level: "A1",
    memory_tip: "Think of a fresh red apple.",
    image_url: "https://images.unsplash.com/photo-1560806887-1e4cd0b6fc6c?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n8",
    german_noun: "Tasche",
    article: "die",
    english_meaning: "bag",
    plural: "die Taschen",
    example_sentence: "Meine Tasche ist schwer.",
    english_translation: "My bag is heavy.",
    cefr_level: "A1",
    memory_tip: "Think of carrying a heavy bag.",
    image_url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n9",
    german_noun: "Beruf",
    article: "der",
    english_meaning: "profession / job",
    plural: "die Berufe",
    example_sentence: "Was ist dein Beruf?",
    english_translation: "What is your profession?",
    cefr_level: "A2",
    memory_tip: "Think of your dream job.",
    image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n10",
    german_noun: "Erfahrung",
    article: "die",
    english_meaning: "experience",
    plural: "die Erfahrungen",
    example_sentence: "Er hat viel Erfahrung in diesem Bereich.",
    english_translation: "He has a lot of experience in this field.",
    cefr_level: "A2",
    memory_tip: "Think of learning from past experiences.",
    image_url: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n11",
    german_noun: "Gespräch",
    article: "das",
    english_meaning: "conversation",
    plural: "die Gespräche",
    example_sentence: "Wir hatten ein langes Gespräch.",
    english_translation: "We had a long conversation.",
    cefr_level: "A2",
    memory_tip: "Think of two people talking deeply.",
    image_url: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n12",
    german_noun: "Fehler",
    article: "der",
    english_meaning: "mistake / error",
    plural: "die Fehler",
    example_sentence: "Aus Fehlern lernt man.",
    english_translation: "One learns from mistakes.",
    cefr_level: "A2",
    memory_tip: "Think of a red cross on a test.",
    image_url: "https://images.unsplash.com/photo-1594322436404-5a0526db4d13?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n13",
    german_noun: "Entscheidung",
    article: "die",
    english_meaning: "decision",
    plural: "die Entscheidungen",
    example_sentence: "Das war eine gute Entscheidung.",
    english_translation: "That was a good decision.",
    cefr_level: "A2",
    memory_tip: "Think of a fork in the road.",
    image_url: "https://images.unsplash.com/photo-1502920514313-52581002a659?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n14",
    german_noun: "Ziel",
    article: "das",
    english_meaning: "goal / destination",
    plural: "die Ziele",
    example_sentence: "Mein Ziel ist es, fließend Deutsch zu sprechen.",
    english_translation: "My goal is to speak German fluently.",
    cefr_level: "A2",
    memory_tip: "Think of an arrow hitting a target.",
    image_url: "https://images.unsplash.com/photo-1499591934245-40b55745b905?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n15",
    german_noun: "Vorteil",
    article: "der",
    english_meaning: "advantage",
    plural: "die Vorteile",
    example_sentence: "Dieses System bietet viele Vorteile.",
    english_translation: "This system offers many advantages.",
    cefr_level: "B1",
    memory_tip: "Think of a plus sign or a thumbs up.",
    image_url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n16",
    german_noun: "Herausforderung",
    article: "die",
    english_meaning: "challenge",
    plural: "die Herausforderungen",
    example_sentence: "Die neue Arbeit ist eine große Herausforderung.",
    english_translation: "The new job is a big challenge.",
    cefr_level: "B1",
    memory_tip: "Think of climbing a steep mountain.",
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n17",
    german_noun: "Ergebnis",
    article: "das",
    english_meaning: "result",
    plural: "die Ergebnisse",
    example_sentence: "Das Ergebnis des Tests war sehr gut.",
    english_translation: "The result of the test was very good.",
    cefr_level: "B1",
    memory_tip: "Think of a report card showing an A+.",
    image_url: "https://images.unsplash.com/photo-1543286386-2e659306cd6c?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n18",
    german_noun: "Zusammenhang",
    article: "der",
    english_meaning: "connection / context",
    plural: "die Zusammenhänge",
    example_sentence: "Es gibt einen klaren Zusammenhang zwischen den Ereignissen.",
    english_translation: "There is a clear connection between the events.",
    cefr_level: "B1",
    memory_tip: "Think of puzzle pieces fitting together.",
    image_url: "https://images.unsplash.com/photo-1581090464707-f28399580b06?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n19",
    german_noun: "Bedingung",
    article: "die",
    english_meaning: "condition",
    plural: "die Bedingungen",
    example_sentence: "Unter dieser Bedingung stimme ich zu.",
    english_translation: "Under this condition, I agree.",
    cefr_level: "B1",
    memory_tip: "Think of a signed contract.",
    image_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "n20",
    german_noun: "Geheimnis",
    article: "das",
    english_meaning: "secret",
    plural: "die Geheimnisse",
    example_sentence: "Das ist ein Geheimnis zwischen uns.",
    english_translation: "That is a secret between us.",
    cefr_level: "B1",
    memory_tip: "Think of someone whispering in an ear.",
    image_url: "https://images.unsplash.com/photo-1520697926135-24d62325c9cc?auto=format&fit=crop&w=400&q=80",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
